name: bestapp
type: php
docroot: www
php_version: "8.4"
webserver_type: nginx-fpm
database:
    type: mariadb
    version: "11.8"
composer_version: "2"
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173
web_extra_daemons:
  - name: vite
    command: "npm run dev"
    directory: /var/www/html
web_environment:
    - NETTE_DEBUG=1